apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker:v1
          name: worker
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"